import {
  Activity,
  Ambulance,
  Bed,
  Building2,
  CalendarClock,
  ClipboardList,
  CreditCard,
  FlaskConical,
  HeartPulse,
  History,
  LayoutDashboard,
  Pill,
  ClipboardPlus,
  ReceiptText,
  Settings,
  Stethoscope,
  ShieldCheck,
  UserRoundCog,
  Users,
  Warehouse,
  WalletCards,
} from "lucide-react";

export const navigation = [
  { label: "Dashboard", path: "/", icon: LayoutDashboard, roles: ["Admin", "Doctor", "Nurse", "Receptionist", "Accountant", "Patient"] },
  { label: "Users", path: "/users", icon: ShieldCheck, roles: ["Admin"] },
  { label: "Patients", path: "/patients", icon: Users, roles: ["Admin", "Doctor", "Receptionist"] },
  { label: "Appointments", path: "/appointments", icon: CalendarClock, roles: ["Doctor", "Receptionist"] },
  { label: "Book Visit", path: "/book-appointment", icon: CalendarClock, roles: ["Patient"] },
  { label: "Doctors", path: "/doctors", icon: Stethoscope, roles: ["Admin"] },
  { label: "Staff", path: "/staff", icon: UserRoundCog, roles: ["Admin"] },
  { label: "Departments", path: "/departments", icon: Building2, roles: ["Admin"] },
  { label: "Admissions", path: "/admissions", icon: Bed, roles: ["Admin", "Nurse"] },
  { label: "Rooms", path: "/rooms", icon: Bed, roles: ["Admin", "Nurse"] },
  { label: "Monitoring", path: "/monitoring", icon: HeartPulse, roles: ["Nurse"] },
  { label: "Vitals", path: "/vitals", icon: Activity, roles: ["Nurse"] },
  { label: "Pharmacy", path: "/pharmacy", icon: Pill, roles: ["Admin"] },
  { label: "Inventory", path: "/inventory", icon: Warehouse, roles: ["Admin"] },
  { label: "Billing", path: "/billing", icon: CreditCard, roles: ["Admin", "Accountant"] },
  { label: "Invoices", path: "/invoices", icon: ReceiptText, roles: ["Accountant"] },
  { label: "Payments", path: "/payments", icon: WalletCards, roles: ["Accountant"] },
  { label: "Laboratory", path: "/laboratory", icon: FlaskConical, roles: ["Admin"] },
  { label: "Records", path: "/records", icon: ClipboardPlus, roles: ["Admin", "Doctor"] },
  { label: "Medical History", path: "/medical-history", icon: History, roles: ["Patient"] },
  { label: "Prescriptions", path: "/prescriptions", icon: Pill, roles: ["Doctor", "Patient"] },
  { label: "Ambulance", path: "/ambulance", icon: Ambulance, roles: ["Admin"] },
  { label: "Reports", path: "/reports", icon: ClipboardList, roles: ["Admin"] },
  { label: "Financial Reports", path: "/financial-reports", icon: ClipboardList, roles: ["Accountant"] },
  { label: "Notifications", path: "/notifications", icon: Activity, roles: ["Admin", "Doctor", "Nurse", "Receptionist", "Accountant", "Patient"] },
  { label: "Activity Logs", path: "/activity", icon: History, roles: ["Admin"] },
  { label: "Permissions", path: "/permissions", icon: ShieldCheck, roles: ["Admin"] },
  { label: "Settings", path: "/settings", icon: Settings, roles: ["Admin"] },
];

export const quickActions = [
  { label: "New Patient", icon: Users },
  { label: "Book Visit", icon: CalendarClock },
  { label: "Vitals", icon: Activity },
  { label: "Invoice", icon: CreditCard },
];
